sudo: false

language: java

script:
  - mvn clean install -U -B -q

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && mvn docker:build && mvn docker:push
  on:
    branch: master